EDLY-2704 Cleaned up unused code to move closer to open edX codebase
edly-io/course-discovery pull request #37
Opened 2021-05-31 12:07 UTC by iam-mhaseeb

**Description: ** This PR cleans up unused code to move closer to open edX codebase.
**JIRA:** https://edlyio.atlassian.net/browse/EDLY-2704

2021-05-31 13:47 UTC, asadmanzoor93 approved these changes

2021-05-31 14:00 UTC, taimoor-ahmed-1 approved these changes

2021-06-01 10:56 UTC, burhandodhy approved these changes

2021-06-01 13:14 UTC, zubair-arbi requested changes
@iam-mhaseeb Please avoid merging this PR until we send the release for this week.

As we will have to test it thoroughly.

2021-06-05 09:44 UTC, zubair-arbi approved these changes
LGTM 👍

2021-06-05 09:52 UTC, merged